name: jknit_gui
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  file_selector: ^1.0.3
  flutter_quill_extensions: ^11.0.0
  re_editor: ^0.7.0
  re_highlight: ^0.0.3
  flutter_markdown: ^0.7.7
  shared_preferences_platform_interface: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
