name: GitHub Actions CI/CD

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [amd64, arm64]

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        # sudo apt update && sudo apt upgrade -y

    - name: Run tests
      run: |
        # make test
