name: GitHub Actions CI/CD

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.7.2"

    - name: Get dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build build-essential libgtk-3-dev
        cd flutter && flutter pub get

    - name: Run tests
      run: |
        cd flutter && flutter test
